# Generated by Django 6.0.5 on 2026-06-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='approver',
            new_name='approved_by',
        ),
    ]
