# Generated by Django 6.0.5 on 2026-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR Manager'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
